//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanGiay
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAY()
        {
            this.CHITIETDATHANGs = new HashSet<CHITIETDATHANG>();
        }
    
        public int MaGiay { get; set; }
        public string TenGiay { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<int> Size { get; set; }
        public string MoTa { get; set; }
        public string AnhGiay { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<int> MaTH { get; set; }
        public Nullable<int> MaLoaiGiay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATHANG> CHITIETDATHANGs { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
        public virtual LOAIGIAY LOAIGIAY { get; set; }
    }
}
